apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-pipeline-deploy
spec:
  resources:
    - name: source-repo
      type: git
    - name: web-image
      type: image
  params:
    - name: image-version
      type: string
    - name: environment
      type: string
    - name: cluster-url
      type: string
    - name: cluster-token
      type: string
  tasks:
    - name: deploy-web
      taskRef:
        name: deploy-using-kubectl
      resources:
        inputs:
          - name: kubernetes-source
            resource: source-repo
          - name: image
            resource: web-image
      params:
        - name: path
          value: /workspace/kubernetes-source/deploy/$(params.environment) #configure: may change according to your source
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"
        - name: environment
          value: $(params.environment)      
        - name: image-version
          value: $(params.image-version)  
        - name: cluster-url
          value: $(params.cluster-url)  
        - name: cluster-token
          value: $(params.cluster-token)  