apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: demo-oiz-git-nikh
spec:
  type: git
  params:
    - name: revision
      value: nikh
    - name: url
      value: https://github.com/niklaushirt/oizdemo
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: demo-oiz-git-master
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/niklaushirt/oizdemo
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: demo-oiz-image-wordpress
spec:
  type: image
  params:
    - name: url
      value: quay.io/niklaushirtibm/wordpress