apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: oiz-demo-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/niklaushirt/oizdemo
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: oiz-demo-git-dev
spec:
  type: git
  params:
    - name: revision
      value: nikh
    - name: url
      value: https://github.com/niklaushirt/oizdemo
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: oiz-demo-image-leeroy-web
spec:
  type: image
  params:
    - name: url
      value: quay.io/niklaushirtibm/wordpress:1.2.0
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: oiz-demo-image-dev
spec:
  type: image
  params:
    - name: url
      value: quay.io/niklaushirtibm/wordpress:dev-1.2.0