apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: oiz-demo-pipeline
spec:
  resources:
    - name: source-repo
      type: git
    - name: web-image
      type: image
  tasks:
    - name: build-skaffold-web
      taskRef:
        name: build-image-from-git-source
      params:
        - name: pathToDockerFile
          value: $(resources.inputs.docker-source.path)/src/Dockerfile
        - name: pathToContext
          value: $(resources.inputs.docker-source.path)/source #configure: may change according to your source
      resources:
        inputs:
          - name: docker-source
            resourceRef:
              name: demo-oiz-git-master
        outputs:
          - name: builtImage
            resourceRef:
              name: demo-oiz-image-wordpress
