apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test-task-run
spec:
  serviceAccountName: oiz-demo-service-account
  taskRef:
    name: build-image-from-git-source
  params:
    - name: pathToDockerFile
      value: $(resources.inputs.docker-source.path)/Dockerfile
    - name: pathToContext
      value: $(resources.inputs.docker-source.path)/source #configure: may change according to your source
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: demo-oiz-git-master
    outputs:
      - name: builtImage
        resourceRef:
          name: demo-oiz-image-wordpress