apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test-task-run
spec:
  serviceAccountName: oiz-demo-service-account
  taskRef:
    name: build-image-from-git-source
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: demo-oiz-git-master
    outputs:
      - name: builtImage
        resourceRef:
          name: demo-oiz-image-wordpress