apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  params:
    - default: $(resources.inputs.docker-source.path)/src/Dockerfile
      description: The path to the dockerfile to build
      name: pathToDockerFile
      type: string
    - default: $(resources.inputs.docker-source.path)/src
      description: |
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      name: pathToContext
      type: string
  resources:
    inputs:
      - name: docker-source
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
    - image: busybox
      name: ls
      resources: {}
      script: ls
    - image: busybox
      name: echo2
      resources: {}
      script: echo $(params.pathToDockerFile)
    - image: busybox
      name: echo
      resources: {}
      script: cat $(params.pathToDockerFile)
    - image: busybox
      name: echo1
      resources: {}
      script: echo $(resources.outputs.builtImage.url)
    - args:
        - '--dockerfile=$(params.pathToDockerFile)'
        - '--destination=$(resources.outputs.builtImage.url)'
        - '--context=$(params.pathToContext)'
      command:
        - /kaniko/executor
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker/
      image: 'gcr.io/kaniko-project/executor:v0.17.1'
      name: build-and-push
      resources: {}
      securityContext:
        runAsUser: 0
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-using-kubectl
spec:
  params:
    - name: path
      type: string
      description: Path to the manifest to apply
    - name: yamlPathToImage
      type: string
      description: |
        The path to the image to replace in the yaml manifest (arg to yq)
  resources:
    inputs:
      - name: kubernetes-source
        type: git
      - name: image
        type: image
  steps:
    - name: echo5
      image: busybox
      script: echo $(resources.inputs.image.url)
    - name: echo24
      image: busybox
      script: cd kubernetes-source && ls
    - name: replace-image
      image: mikefarah/yq
      command: ["yq"]
      args:
        - "w"
        - "-i"
        - "$(params.path)/deployment.yaml"
        - "$(params.yamlPathToImage)"
        - "$(resources.inputs.image.url)"
    - name: finalyaml
      image: busybox
      script: cat $(params.path)/deployment.yaml
    - name: delete-previous
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "delete"
        - "-f"
        - "$(params.path)"
        - "-n"
        - "default"
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(params.path)"
        - "-n"
        - "default"