apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tutorial-pipeline
spec:
  resources:
    - name: source-repo
      type: git
    - name: web-image
      type: image
  tasks:
    - name: build-oiz-demo-web
      taskRef:
        name: build-docker-image-from-git-source
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: web-image
    - name: deploy-web
      taskRef:
        name: deploy-using-kubectl
      resources:
        inputs:
          - name: kubernetes-source
            resource: source-repo
          - name: image
            resource: web-image
            from:
              - build-oiz-demo-web
      params:
        - name: path
          value: /workspace/kubernetes-source/deploy/prod #configure: may change according to your source
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"