apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tutorial-pipeline-run-1
spec:
  serviceAccountName: oiz-demo-service-account
  pipelineRef:
    name: tutorial-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: oiz-demo-git
    - name: web-image
      resourceRef:
        name: oiz-demo-image-leeroy-web