apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: oiz-demo-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/niklaushirt/oizdemo
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: oiz-demo-git-dev-nikh
spec:
  type: git
  params:
    - name: revision
      value: nikh
    - name: url
      value: https://github.com/niklaushirt/oizdemo
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: oiz-demo-image
spec:
  type: image
  params:
    - name: url
      value: quay.io/niklaushirtibm/wordpress
