apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-dev-run-1
spec:
  serviceAccountName: oiz-demo-service-account
  pipelineRef:
    name: demo-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: oiz-demo-git-dev
    - name: web-image
      resourceRef:
        name: oiz-demo-image
  params:
    - name: image-version
      value: "200603"
    - name: environment
      value: "dev"