apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: oiz-demo-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/niklaushirt/oizdemo
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: oiz-demo-git-dev-nikh
spec:
  type: git
  params:
    - name: revision
      value: nikh
    - name: url
      value: https://github.com/niklaushirt/oizdemo
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: oiz-demo-image
spec:
  type: image
  params:
    - name: url
      value: quay.io/niklaushirtibm/wordpress
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: local-cluster
spec:
  type: cluster
  params:
    - name: url
      value: https://c100-e.eu-de.containers.cloud.ibm.com:30761 # url to the cluster master node
    - name: cadata
      value: 1yYDIbgCV-1B4VUh9M1XPFfjWn7dJnNIGzDPK5eyrlc
    - name: token
      value: 1yYDIbgCV-1B4VUh9M1XPFfjWn7dJnNIGzDPK5eyrlc
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: prod-cluster
spec:
  type: cluster
  params:
    - name: url
      value: https://c100-e.eu-de.containers.cloud.ibm.com:32764 # url to the cluster master node
    - name: cadata
      value: CtWGTAQX4nrIDdGvWVVywtTw_35zm-c3GdkurtE-V_s
    - name: token
      value: CtWGTAQX4nrIDdGvWVVywtTw_35zm-c3GdkurtE-V_s
