apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-pipeline-complete
spec:
  resources:
    - name: source-repo
      type: git
    - name: web-image
      type: image
    - name: local-cluster
      type: cluster
    - name: prod-cluster
      type: cluster
  params:
    - name: image-version
      type: string
    - name: environment
      type: string
    - name: cluster-url
      type: string
      default: $(resources.local-cluster.url)
    - name: cluster-token
      type: string
      default: $(resources.local-cluster.token)
    - name: cluster-prod-url
      default: $(resources.prod-cluster.url)
      type: string
    - name: cluster-prod-token
      default: $(resources.prod-cluster.token)
      type: string
  tasks:


    - name: build-oiz-demo
      taskRef:
        name: build-docker-image-from-git-source
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: web-image
      params:
      - name: environment
        value: dev        
      - name: image-version
        value: $(params.image-version)


    - name: deploy-dev
      taskRef:
        name: deploy-using-kubectl
      runAfter:
        - build-oiz-demo
      resources:
        inputs:
          - name: kubernetes-source
            resource: source-repo
          - name: image
            resource: web-image
            from:
              - build-oiz-demo
      params:
        - name: path
          value: /workspace/kubernetes-source/deploy/$(params.environment) #configure: may change according to your source
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"
        - name: environment
          value: dev  
        - name: image-version
          value: $(params.image-version)  
        - name: cluster-url
          value: $(params.cluster-url)  
        - name: cluster-token
          value: $(params.cluster-token)  



    - name: smoke-tests
      taskRef:
        name: smoke-tests
      runAfter:
        - deploy-dev
      resources:
        inputs:
          - name: kubernetes-source
            resource: source-repo
          - name: image
            resource: web-image
      params:
        - name: path
          value: /workspace/kubernetes-source/deploy/$(params.environment) #configure: may change according to your source
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"
        - name: environment
          value: dev  
        - name: image-version
          value: $(params.image-version)  
        - name: cluster-url
          value: $(params.cluster-url)  
        - name: cluster-token
          value: $(params.cluster-token)  




    - name: deploy-test
      taskRef:
        name: deploy-using-kubectl
      runAfter:
        - smoke-tests
      resources:
        inputs:
          - name: kubernetes-source
            resource: source-repo
          - name: image
            resource: web-image
            from:
              - build-oiz-demo
      params:
        - name: path
          value: /workspace/kubernetes-source/deploy/$(params.environment) #configure: may change according to your source
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"
        - name: environment
          value: test
        - name: image-version
          value: $(params.image-version)  
        - name: cluster-url
          value: $(params.cluster-url)  
        - name: cluster-token
          value: $(params.cluster-token)  



    - name: integration-tests
      taskRef:
        name: integration-tests
      runAfter:
        - deploy-test
      resources:
        inputs:
          - name: kubernetes-source
            resource: source-repo
          - name: image
            resource: web-image
      params:
        - name: path
          value: /workspace/kubernetes-source/deploy/$(params.environment) #configure: may change according to your source
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"
        - name: environment
          value: dev  
        - name: image-version
          value: $(params.image-version)  
        - name: cluster-url
          value: $(params.cluster-url)  
        - name: cluster-token
          value: $(params.cluster-token)  



    - name: deploy-prod
      taskRef:
        name: deploy-using-kubectl
      runAfter:
        - integration-tests
      resources:
        inputs:
          - name: kubernetes-source
            resource: source-repo
          - name: image
            resource: web-image
            from:
              - build-oiz-demo
      params:
        - name: path
          value: /workspace/kubernetes-source/deploy/$(params.environment) #configure: may change according to your source
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"
        - name: environment
          value: prod
        - name: image-version
          value: $(params.image-version)  
        - name: cluster-url
          value: $(params.cluster-prod-url)  
        - name: cluster-token
          value: $(params.cluster-prod-token)  
