apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: git-pipeline-local-run
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipeline-run-local-$(params.gitrevision)
      spec:
        serviceAccountName: oiz-demo-service-account
        pipelineRef:
          name: demo-pipeline-local
        resources:
          - name: source-repo
            resourceRef:
              name: oiz-demo-git-dev-nikh
          - name: web-image
            resourceRef:
              name: oiz-demo-image
          - name: local-cluster
            resourceRef:
              name: local-cluster
        params:
          - name: image-version
            value: oizdemo-200608
          - name: environment
            value: "nikh"
          - name: cluster-url
            value: https://c100-e.eu-de.containers.cloud.ibm.com:30761
          - name: cluster-token
            value: w5L0nTig8E3VbHv94XfC7I08UEELNbebi3Ki4vgaVdQ
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: git-pipeline-local-binding
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.url)
  - name: contenttype
    value: $(header.Content-Type)
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
stringData:
  secretToken: "1234567"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener-interceptor
spec:
  serviceAccountName: oiz-demo-service-account
  triggers:
    - name: github-listener
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: secretToken
            eventTypes:
              - push
      bindings:
        - name:  git-pipeline-local-binding
      template:
        name: git-pipeline-local-run
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: github
  namespace: oiz-demo-pipeline
spec:
  to:
    kind: Service
    name: el-github-listener-interceptor
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None
