apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  resources:
    - name: source-repo
      type: git
    - name: web-image
      type: image
  params:
    - name: image-version
      type: string
    - name: environment
      type: string
  tasks:
    - name: build-oiz-demo-web
      taskRef:
        name: build-docker-image-from-git-source
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: web-image
      params:
      - name: environment
        value: $(params.environment)        
      - name: image-version
        value: $(params.image-version)
    - name: deploy-web
      taskRef:
        name: deploy-using-kubectl
      resources:
        inputs:
          - name: kubernetes-source
            resource: source-repo
          - name: image
            resource: web-image
            from:
              - build-oiz-demo-web
      params:
        - name: path
          value: /workspace/kubernetes-source/deploy/$(params.environment) #configure: may change according to your source
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"
        - name: environment
          value: $(params.environment)      
        - name: image-version
          value: $(params.image-version)  